/******************** (C) COPYRIGHT 2021 STMicroelectronics ********************
* File Name         : bluenrg_lp_hw_config.h
* Author            : RF Application team
* Version           : 1.0.0
* Date              : 27-October-2021
* Description       : File generated by the IO Mapper tool
********************************************************************************
* THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS
* WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE TIME.
* AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY DIRECT,
* INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING FROM THE
* CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE CODING
* INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS.
*******************************************************************************/

/* Includes ------------------------------------------------------------------*/

/* Private includes ----------------------------------------------------------*/
#include "rf_driver_ll_adc.h"
#include "rf_driver_ll_bus.h"
#include "rf_driver_ll_cortex.h"
#include "rf_driver_ll_dma.h"
#include "rf_driver_ll_exti.h"
#include "rf_driver_ll_gpio.h"
#include "rf_driver_ll_i2c.h"
#include "rf_driver_ll_iwdg.h"
#include "rf_driver_ll_lpuart.h"
#include "rf_driver_ll_pwr.h"
#include "rf_driver_ll_rcc.h"
#include "rf_driver_ll_rng.h"
#include "rf_driver_ll_rtc.h"
#include "rf_driver_ll_spi.h"
#include "rf_driver_ll_tim.h"
#include "rf_driver_ll_system.h"
#include "rf_driver_ll_utils.h"
#include "rf_driver_ll_usart.h"
#include "bluenrg_lpx.h"

/* Private typedef -----------------------------------------------------------*/
/* Private define ------------------------------------------------------------*/












/* Interrupts enable */


/* Private macro -------------------------------------------------------------*/
/* Private variables ---------------------------------------------------------*/
/* Private function prototypes -----------------------------------------------*/
/* Private user code ---------------------------------------------------------*/
/* External variables --------------------------------------------------------*/
/* Public function prototypes ------------------------------------------------*/
void bluenrg_lp_initialization(void);
